global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.JSInterop;
global using Microsoft.AspNetCore.SignalR.Client;
global using Blazored.LocalStorage;
global using MudBlazor;
global using fgciams.Store;
global using fgciams.Common;
global using fgciams.service.PettyCashServices;
global using fgciams.service.LiquidationServices;
global using fgciams.service.VoucherServices;
global using fgciams.service.GlobalServices;
global using fgciams.service.RequestForPaymentService;
global using fgciams.domain.clsEmployee;
global using fgciams.domain.clsUserAccount;
global using fgciams.domain.clsAccountingStatus;
global using fgciams.domain.clsFilterParameter;
global using fgciams.domain.clsEnums;
global using fgciams.domain.clsPettyCash;
global using fgciams.domain.clsLiquidation;
global using fgciams.domain.clsCheck;
global using fgciams.domain.clsDebit;
global using fgciams.domain.clsRequest;
global using fgciams.domain.clsProject;
global using fgciams.domain.clsCollection;
global using fgciams.domain.clsVoucher;
global using fgciams.domain.clsNotification;
global using fgciams.Pages.ModulePages.PettyCashPage;
global using fgciams.Pages.ModulePages.CheckWriterPage;
global using fgciams.Pages.ModulePages.VoucherPage;
using fgciams;
using System.Net.Http;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using MudBlazor.Services;
using fgciams.domain.clsAppstate;
using fgciams.service.AccountingStatusServices;
using fgciams.service.UserAccountServices;
using fgciams.service.ModeOfPaymentServices;
using fgciams.service.DivisionServices;
using fgciams.service.BankServices;
using fgciams.service.ProjectChargingLineServices;
using fgciams.service.RequestTypeServices;
using fgciams.service.SubContractorCompanyServices;
using fgciams.service.SubContractorPositionServices;
using fgciams.service.SubConGeneralInformationServices;
using fgciams.service.BillingDocumentServices;
using fgciams.service.PayeeCategoryServices;
using fgciams.service.PayeeServices;
using fgciams.service.AccountingPOBillingServices;
using fgciams.service.ExpenseLineServices;
using fgciams.service.AccountTypeServices;
using fgciams.service.AccountingLineServices;
using fgciams.service.AccountLineTypeServices;
using fgciams.service.CheckServices;
using fgciams.service.VoucherRouteBatchServices;
using fgciams.service.TaxCodeServices;
using fgciams.service.SupplierServices;
using fgciams.service.TermsOfPaymentServices;
using fgciams.service.MuniCityServices;
using fgciams.service.VATServices;
using fgciams.service.BIRServices;
using fgciams.service.ScopeOfWorkServices;
using fgciams.service.CollectionServices;
using fgciams.service.BankDepositServices;
using fgciams.service.LedgerServices;
using fgciams.service.DebitServices;
using fgciams.service.VoucherRouteTagServices;
using fgciams.service.JournalServices;
using fgciams.service.AccessLevelServices;
using fgciams.service.CustomerServices;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.Configuration.GetValue<string>("BaseAPIUrl")) });
builder.Services.AddBlazoredLocalStorage();
builder.Services.AddMudServices();
builder.Services.AddScoped<ApplicationState>();
builder.Services.AddScoped<IAccountingStatusService, AccountingStatusService>();
builder.Services.AddScoped<IModeOfPaymentService, ModeOfPaymentService>();
builder.Services.AddScoped<IUserAccountService, UserAccountService>();
builder.Services.AddScoped<IRequestForPaymentService, RequestForPaymentService>();
builder.Services.AddScoped<IGlobalService, GlobalService>();
builder.Services.AddScoped<IDivisionService, DivisionService>();
builder.Services.AddScoped<IBankService, BankService>();
builder.Services.AddScoped<IProjectChargingLineService, ProjectChargingLineService>();
builder.Services.AddScoped<IRequestTypeService, RequestTypeService>();
builder.Services.AddScoped<ISubContractorCompanyService, SubContractorCompanyService>();
builder.Services.AddScoped<ISubContractorPositionService, SubContractorPositionService>();
builder.Services.AddScoped<ISubConGeneralInformationService, SubConGeneralInformationService>();
builder.Services.AddScoped<IBillingDocumentService, BillingDocumentService>();
builder.Services.AddScoped<IPayeeCategoryService, PayeeCategoryService>();
builder.Services.AddScoped<IPayeeService, PayeeService>();
builder.Services.AddScoped<IAccountingPOBillingService, AccountingPOBillingService>();
builder.Services.AddScoped<ILiquidationService, LiquidationService>();
builder.Services.AddScoped<IPayeeService, PayeeService>();  
builder.Services.AddScoped<IPettyCashService, PettyCashService>();
builder.Services.AddScoped<IExpenseLineService, ExpenseLineService>();
builder.Services.AddScoped<IVoucherService, VoucherService>();
builder.Services.AddScoped<IAccountTypeService, AccountTypeService>();
builder.Services.AddScoped<IAccountingLineService, AccountingLineService>();
builder.Services.AddScoped<IAccountLineTypeService, AccountLineTypeService>();
builder.Services.AddScoped<ICheckService, CheckService>();
builder.Services.AddScoped<IVoucherRouteService, VoucherRouteService>();
builder.Services.AddScoped<IVoucherRouteBatchService, VoucherRouteBatchService>();
builder.Services.AddScoped<ITaxCodeService, TaxCodeService>();
builder.Services.AddScoped<ISupplierService, SupplierService>();
builder.Services.AddScoped<ITermsOfPaymentService, TermsOfPaymentService>();
builder.Services.AddScoped<IMuniCityService, MuniCityService>();
builder.Services.AddScoped<IVATService, VATService>();
builder.Services.AddScoped<IBIRService,BIRService>();
builder.Services.AddScoped<IScopeOfWorkService,ScopeOfWorkService>();
builder.Services.AddScoped<ICollectionService,CollectionService>();
builder.Services.AddScoped<IBankDepositService,BankDepositService>();
builder.Services.AddScoped<ILedgerService,LedgerService>();
builder.Services.AddScoped<IDebitService,DebitService>();
builder.Services.AddScoped<IVoucherRouteTagUserService,VoucherRouteTagUserService>();
builder.Services.AddScoped<IJournalService,JournalService>();
builder.Services.AddScoped<IAccessLevelService,AccessLevelService>();
builder.Services.AddScoped<ICustomerService, CustomerService>();

//Microsoft.AspNetCore.Components.Authorization;
builder.Services.AddOptions();
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<AuthenticationStateProvider, CustomAuthStateProvider>();
//

await builder.Build().RunAsync();
